version: '2'
services:
  sample-backend:
    build: ./backend
    image: server:latest
    ports:
      - "8081:8081"
    container_name: python-backend
  sample-frontend:
    build: ./front
    image: angular2:latest
    container_name: angular2-frontend
    ports:
      - "3000:8080"
    links:
      - sample-backend
    depends_on:
      - sample-backend
