version: '2'
services:
  backend-s:
    build: ./backend
    image: ansrivas/server:latest
    container_name: backend-c
  frontend-s:
    build: ./front
    image: ansrivas/frontend:latest
    container_name: frontend-c
    ports:
      - "3000:80"
    links:
      - backend-s
    depends_on:
      - backend-s
